### PR TITLE
chore: add jenkins

### LINKED ISSUE #5: Enable CI
Would prefer to have some automated testing here ;) @libp2p/dx

### PR DESCRIPTION
**Pull request by jacobheun**
Adds the Jenkinsfile.

Fixes #5.

### CODE REVIEW

**Comment by jacobheun** [comment]
Builds are running https://ci.ipfs.team/blue/organizations/jenkins/libp2p%2Fjs-libp2p-stardust/detail/PR-6/1/pipeline/169, just need to get CI team permissions fixed for the status post back.

**Comment by jacobheun** [comment]
Ci is integrated now. Build is failing, but that should probably be fixed in a subsequent PR.

**Review by mkg20001 — APPROVED** [review]
LGTM

**Comment by mkg20001** [comment]
Build fails because of #7

**Pull request merged**
